SELECT TOP 1000 [FirstCol]
      ,[SecondCol]
  FROM [EncryptTest].[dbo].[TestTable]

  CREATE MASTER KEY ENCRYPTION
  BY PASSWORD='SQL'

  CREATE CERTIFICATE EncryptCerti
  WITH SUBJECT='SQL'


  CREATE SYMMETRIC KEY TESTTABLEKEY
  WITH ALGORITHM=TRIPLE_DES ENCRYPTION
  BY CERTIFICATE EncryptCerti


ALTER TABLE [TestTable]
ADD EncryptCol VARBINARY(256)

SELECT * FROM [TestTable]

OPEN SYMMETRIC KEY TESTTABLEKEY DECRYPTION
BY CERTIFICATE EncryptCerti

UPDATE [TestTable] 
SET EncryptCol=ENCRYPTBYKEY(KEY_GUID('TESTTABLEKEY'),SecondCol)


SELECT t.FirstCol,t.SecondCol,t.EncryptCol,CONVERT(VARCHAR(50),DECRYPTBYKEY(t.EncryptCol))AS DecryptCol 
FROM [TestTable] t


DECLARE @NAME VARCHAR(250)
SET @NAME='RAVI ARORA'

INSERT INTO [TestTable] values(6,@NAME,ENCRYPTBYKEY(KEY_GUID('TESTTABLEKEY'),@NAME))
